<h2><?php echo $this->__("1. JOIN") ?></h2>
<p><?php echo $this->__("Create your Entangled Fan Points account.") ?></p>
<a class="button join-today"><?php echo $this->__("Create account") ?></a>
<p><?php echo $this->__("Be sure to sign-in first!") ?></p>
<a class="button join-today"><?php echo $this->__("Sign In") ?></a>
<h2><?php echo $this->__("2. SHOP") ?></h2>
<div>
    <p><?php echo $this->__("You’ll earn Fan Points for every purchase you make at") ?>
        <a href="<?php echo $this->getBaseUrl() ?>"><?php echo $this->__("the Entangled shop") ?></a>
    <p><?php echo $this->__("Whether at home, or on-the-go, all the books you buy from Entangled add up.") ?>
</div>
<h2><?php echo $this->__("3. REDEEM") ?></h2>
<div>
    <p><?php echo $this->__("Every dollar = 100 points.") ?></p>
    <p><?php echo $this->__("1000 points = $1 credit automatically added to your account.") ?></p>
    <p><?php echo $this->__("At checkout, you’ll see an option to apply your accumulated points and receive a cash discount on your next shopping experience!") ?></p>
    <p><?php echo $this->__("It’s that simple.") ?></p>
</div>
