<?php
/**
 * @var Mage_Page_Block_Html_Header $this
 */
?>
<?php
	$theme = Mage::helper('ultimo');

	//Check if search box is displayed inside User Menu
	if ($theme->getCfg('header/search_position') === 'userMenu')
	{
		$searchHtml = $this->getChildHtml('search_wrapper');
		if ($searchHtml)
		{
			switch ($theme->getCfg('header/search_in_user_menu_position'))
			{
				case '1':
					$p[0] = $searchHtml;
					break;
				case '2':
					$p[1] = $searchHtml;
					break;
				case '3':
					$p[2] = $searchHtml;
					break;
				case '4':
					$p[3] = $searchHtml;
					break;
			}

			//Set flag which indicates that search box exists and is displayed
			if (Mage::registry('headerDisplaySearch') === NULL)
			{
				Mage::register('headerDisplaySearch', true);
			}
		}
	}

	//Additional line break inside User Menu
	$lineBreakHtml = '<div class="line-break-after"></div>';
	switch ($theme->getCfg('header/toplinks_break_position'))
	{
		case '0':
			break;
		case '30':
			$lineBreak[0] = $lineBreakHtml;
			break;
		case '31':
			$lineBreak[1] = $lineBreakHtml;
			break;
		case '32':
			$lineBreak[2] = $lineBreakHtml;
			break;
		case '33':
			$lineBreak[3] = $lineBreakHtml;
			break;
		case '34':
			$lineBreak[4] = $lineBreakHtml;
			break;
		case '35':
			$lineBreak[5] = $lineBreakHtml;
			break;
	}

	//Account links
	$accountLinksHtml = '';

		//Deprecated
		//Additional custom links
		if ($tmpHtml = $this->getChildHtml('block_header_top_links2'))
		{
			$accountLinksHtml .= $tmpHtml;
		}

		//Default Magento Top Links
		if ($theme->getCfg('magento_blocks/top_links'))
		{
			$accountLinksHtml .= $this->getChildHtml('topLinks');
		}

		//Additional custom links
		if ($tmpHtml = $this->getChildHtml('block_header_top_links'))
		{
			$accountLinksHtml .= $tmpHtml;
		}

		if ($accountLinksHtml) 
		{
			//Set flag which indicates that block with account links (including Top Links) exists and is displayed
			if (Mage::registry('headerDisplayAccountLinks') === NULL)
			{
				Mage::register('headerDisplayAccountLinks', true);
			}
		}

	//Mini cart
	$cartHtml = '';
	if ($theme->getCfg('header/cart_position') === 'userMenu')
	{
		$cartHtml = $this->getChildHtml('cart_sidebar');
		if ($cartHtml)
		{
			//Set flag which indicates that mini cart exists and is displayed
			if (Mage::registry('headerDisplayMiniCart') === NULL)
			{
				Mage::register('headerDisplayMiniCart', true);
			}
		}
	}

	//Mini compare
	$compareHtml = '';
	/*
	if ($theme->getCfg('header/compare_position') === 'userMenu' && $theme->getCfg('header/compare'))
	{
		$compareHtml = $this->getChildHtml('compareMini');
		if ($compareHtml)
		{
			//Set flag which indicates that mini compare exists and is displayed
			if (Mage::registry('headerDisplayMiniCompare') === NULL)
			{
				Mage::register('headerDisplayMiniCompare', true);
			}
		}
	}
*/
?>
<div id="user-menu-wrapper-regular">
	<div id="user-menu" class="user-menu">
		<?php if (isset($p[0])) echo $p[0]; ?>

		<?php if (isset($lineBreak[0])) echo $lineBreak[0]; ?>

		<?php if ($cartHtml): //Mini cart ?>
			<?php echo $cartHtml; ?>
		<?php endif; ?>

		<?php if (isset($lineBreak[1])) echo $lineBreak[1]; ?>

		<?php if (isset($p[1])) echo $p[1]; ?>
		
		<?php if (isset($lineBreak[2])) echo $lineBreak[2]; ?>

		<?php if ($compareHtml): //Mini compare ?>
			<?php echo $compareHtml; ?>
		<?php endif; ?>

		<?php if (isset($lineBreak[3])) echo $lineBreak[3]; ?>

		<?php if (isset($p[2])) echo $p[2]; ?>
		
		<?php if (isset($lineBreak[4])) echo $lineBreak[4]; ?>

		<?php if ($accountLinksHtml): //Account links ?>
			<div id="account-links-wrapper-regular">
				<div id="header-account" class="top-links links-wrapper-separators-left skip-content skip-content--style">
					<?php echo $accountLinksHtml; ?>
				</div>
			</div>
		<?php endif; ?>

		<?php if (isset($lineBreak[5])) echo $lineBreak[5]; ?>

		<?php if (isset($p[3])) echo $p[3]; ?>

	</div> <!-- end: user-menu -->
</div>