<?php
/**
 * Custom Publisher Models
 * 
 * Add custom model types, such as author, which can be used as a product
 * attribute while proviting additional details.
 * 
 * @license 	http://opensource.org/licenses/gpl-license.php GNU General Public License, Version 3
 * @copyright	Steven Brown March 12, 2016
 * @author		Steven Brown <steveb.27@outlook.com>
 */
 
class SteveB27_Publish_Model_Resource_Setup extends Mage_Eav_Model_Entity_Setup
{
    public function getDefaultEntities()
    {
        $entities = array(
            'author' => array(
                'entity_model' 					=> 'publish/author',
                'attribute_model'               => 'publish/resource_eav_attribute',
				'table'                         => 'publish/author',
				'additional_attribute_table'    => 'publish/publish_eav_attribute',
				'entity_attribute_collection'   => 'publish/attribute_collection',
				'attributes' => array(
                    'name' => array(
                        'type' 				=> 'varchar',
                        'backend' 			=> '',
                        'frontend' 			=> '',
                        'label' 			=> 'Name',
                        'input' 			=> 'text',
                        'source' 			=> '',
                        'global' 			=> Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
                        'required' 			=> '1',
                        'user_defined' 		=> '0',
                        'default' 			=> '',
                        'unique' 			=> '0',
                        'position'       	=> '10',
                        'note'           	=> '',
                        'is_visible'        	=> '1',
                        'is_wysiwyg_enabled'	=> '0',
                    ),
                    'email' => array(
                        'type' 				=> 'varchar',
                        'backend' 			=> '',
                        'frontend' 			=> '',
                        'label' 			=> 'Author eMail',
                        'input' 			=> 'text',
                        'source' 			=> '',
                        'global' 			=> Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
                        'required' 			=> '1',
                        'user_defined' 		=> '0',
                        'default' 			=> '',
                        'unique' 			=> '1',
                        'position'       	=> '15',
                        'note'           	=> '',
                        'is_visible'        	=> '1',
                        'is_wysiwyg_enabled'	=> '0',
                    ),
                    'image' => array(
                        'type' 				=> 'file',
                        'backend' 			=> 'publish/attribute_backend_image',
                        'frontend' 			=> '',
                        'label' 			=> 'Image',
                        'input' 			=> 'image',
                        'source' 			=> '',
                        'global' 			=> Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
                        'required' 			=> '',
                        'user_defined' 		=> '0',
                        'default' 			=> '',
                        'unique' 			=> '0',
                        'position'       	=> '20',
                        'note'           	=> '',
                        'is_visible'        	=> '1',
                        'is_wysiwyg_enabled'	=> '0',
                    ),
                    'biography' => array(
                        'type' 				=> 'text',
                        'backend' 			=> '',
                        'frontend' 			=> '',
                        'label' 			=> 'Biography',
                        'input' 			=> 'textarea',
                        'source' 			=> '',
                        'global' 			=> Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
                        'required' 			=> '',
                        'user_defined' 		=> '0',
                        'default' 			=> '',
                        'unique' 			=> '0',
                        'position'       	=> '30',
                        'note'           	=> '',
                        'is_visible'        	=> '1',
                        'is_wysiwyg_enabled'	=> '1',
                    ),
                    'status' => array(
                        'type'           	=> 'int',
                        'backend'        	=> '',
                        'frontend'       	=> '',
                        'label'          	=> 'Enabled',
                        'input'          	=> 'select',
                        'source'         	=> 'eav/entity_attribute_source_boolean',
                        'global'         	=> Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
                        'required'       	=> '',
                        'user_defined'   	=> '0',
                        'default'        	=> '',
                        'unique'         	=> '0',
                        'position'       	=> '500',
                        'note'           	=> '',
                        'is_visible'        	=> '1',
                        'is_wysiwyg_enabled'	=> '0',
                    ),
                    'url_key' => array(
                        'type'           	=> 'varchar',
                        'backend'        	=> 'publish/attribute_backend_urlkey',
                        'frontend'       	=> '',
                        'label'          	=> 'URL key',
                        'input'          	=> 'text',
                        'source'         	=> '',
                        'global'         	=> Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
                        'required'       	=> '',
                        'user_defined'   	=> '0',
                        'default'        	=> '',
                        'unique'         	=> '0',
                        'position'       	=> '40',
                        'note'           	=> 'Url will be /&lt;prefix&gt;/&lt;this&gt;.suffix (IE: /author/urlkey.html)',
                        'is_visible'        	=> '1',
                        'is_wysiwyg_enabled'	=> '0',
                    ),
                    'in_rss' => array(
                        'type'           	=> 'int',
                        'backend'        	=> '',
                        'frontend'       	=> '',
                        'label'          	=> 'In RSS',
                        'input'          	=> 'select',
                        'source'         	=> 'eav/entity_attribute_source_boolean',
                        'global'         	=> Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
                        'required'       	=> '',
                        'user_defined'   	=> '0',
                        'default'        	=> '',
                        'unique'         	=> '0',
                        'position'       	=> '400',
                        'note'           	=> '',
                        'is_visible'        	=> '1',
                        'is_wysiwyg_enabled'	=> '0',
                    ),
                    'meta_title' => array(
                        'type'           	=> 'varchar',
                        'backend'        	=> '',
                        'frontend'       	=> '',
                        'label'          	=> 'Meta title',
                        'input'          	=> 'text',
                        'source'         	=> '',
                        'global'         	=> Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
                        'required'       	=> '',
                        'user_defined'   	=> '0',
                        'default'        	=> '',
                        'unique'         	=> '0',
                        'position'       	=> '80',
                        'note'           	=> '',
                        'is_visible'        	=> '1',
                        'is_wysiwyg_enabled'	=> '0',
                    ),
                    'meta_keywords' => array(
                        'type'           	=> 'text',
                        'backend'        	=> '',
                        'frontend'       	=> '',
                        'label'          	=> 'Meta keywords',
                        'input'          	=> 'textarea',
                        'source'         	=> '',
                        'global'         	=> Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
                        'required'       	=> '',
                        'user_defined'   	=> '0',
                        'default'        	=> '',
                        'unique'         	=> '0',
                        'position'       	=> '90',
                        'note'           	=> '',
                        'is_visible'        	=> '1',
                        'is_wysiwyg_enabled'	=> '0',
                    ),
                    'meta_description' => array(
                        'type'           	=> 'text',
                        'backend'        	=> '',
                        'frontend'       	=> '',
                        'label'          	=> 'Meta description',
                        'input'          	=> 'textarea',
                        'source'         	=> '',
                        'global'         	=> Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
                        'required'       	=> '',
                        'user_defined'   	=> '0',
                        'default'        	=> '',
                        'unique'         	=> '0',
                        'position'       	=> '100',
                        'note'           	=> '',
                        'is_visible'        	=> '1',
                        'is_wysiwyg_enabled'	=> '0',
                    ),

                ),
            )
        );
        return $entities;
    }
}
