<div class="container testimonal-container">
    <div class="row">
        <div class="col-sm-3">
            <div class="sidebar">
                <div class="sidebar-block testemonial_info">
                    <?php echo $this->getAuthorWidgetHtml();?>
                </div>
            </div>
        </div>
        <div class="col-sm-9">
            <div class="carousel_container">
                <?php echo $this->getSliderHtml(); ?>
            </div>
        </div>
    </div>
</div>