<?php
    $categories = $this->getGenresData();
    $imageHelper = Mage::helper('catalog/image');
    $customHelper = Mage::helper('entangled_custom');
?>
<section class="genres-container container-fluid">
    <div class="container">
        <div class="title-container">
            <h4 class="title">SHOP BY CATEGORY</h4>
            <h4 class="desc">From small town heroes to sexy billionaires to teens saving the world... We've got the book for you!</h4>
        </div>
        <div class="row">
            <?php $i=0; ?>
            <?php foreach($categories as $category): ?>
                <?php
                    $class = "";
                    if($i == 4) { $class = "col-md-push-4 col-lg-push-0"; }
                    if($i == 5) { $class = "col-md-pull-4 col-lg-pull-0"; }
                ?>
                <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3 item <?php echo $class ?>" ontouchstart="this.classList.toggle('hover');">
                    <a href="<?php echo $customHelper->getLayerUrl("book_genre",$category->getName()) ?>" >
                        <div class="body">
                            <img class="background-book" src="<?php echo $imageHelper->init($category->getProducts()->getFirstItem(),'small_image')->resize(260,390)?>" alt="<?php echo $this->__($category->getProducts()->getFirstItem()->getName()) ?>"/>
                            <div class="subtitle"><span><?php echo $category->getName() ?></span></div>
                            <div class="shop-hover animate">
                                <i class="glyphicon glyphicon-shopping-cart"></i>
                                <span><?php echo $this->__('Shop now') ?></span>
                            </div>
                        </div>
                    </a>
                </div>
                <?php if($i == 4):?>
                    <div class="hidden-xs hidden-sm col-md-4 col-md-pull-4 col-lg-3 col-lg-pull-0 item promo-space" ontouchstart="this.classList.toggle('hover');">
                        <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('genre-ad-block-1')->toHTML(); ?>
                    </div>
                    <div class="hidden-xs hidden-sm col-md-4 col-md-push-4 col-lg-3 col-lg-push-0 item promo-space" ontouchstart="this.classList.toggle('hover');">
                        <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('genre-ad-block-2')->toHTML(); ?>
                    </div>
                <?php endif; ?>
                <?php $i++; ?>
            <?php endforeach; ?>
            <div class="col-xs-12 col-sm-6 hidden-md hidden-lg item promo-space" ontouchstart="this.classList.toggle('hover');">
                <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('genre-ad-block-1')->toHTML(); ?>
            </div>
            <div class="col-xs-12 col-sm-6 hidden-md hidden-lg item promo-space" ontouchstart="this.classList.toggle('hover');">
                <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('genre-ad-block-2')->toHTML(); ?>
            </div>
        </div>
    </div>
</section>