<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2016 Amasty (https://www.amasty.com)
 * @package Amasty_Base
 */
?>
<div class="ambase-debug-header"><?php echo $this->__("General")?></div>
<div class="ambase-debug-section">
    <table cellspacing="0">
        <tr>
            <td><?php echo $this->__("Compilation")?></td>
            <td>
                <?php if ($this->isCompilationEnabled()) { ?>
                    <span class="red"><?php echo $this->__("On")?></span>
                <?php } else { ?>
                    <span class="green"><?php echo $this->__("Off")?></span>
                <?php }?>
            </td>
        </tr>
        <tr>
            <td><?php echo $this->__("Disabled output")?></td>
            <td>
                <?php if (count($this->getDisableModulesOutput()) > 0) {?>
                <div class="red"><?php 
                    foreach($this->getDisableModulesOutput() as $module){
                       echo $module['name']."<br/>";
                    }
                ?></div>
                <?php } else { ?>
                <span class="green"><?php echo $this->__("No")?></span>
                
                <?php } ?>           
            </td>
        </tr>
        <tr>
            <td><?php echo $this->__("Cron")?></td>
            <td><?php
            $crontabConfig = $this->getCrontabConfig();
            if (count($crontabConfig) === 0){
                echo '<div class="red">';
                echo $this->__('No cron jobs found') . "</div>";
                echo "<a target='_blank' href='https://support.amasty.com/index.php?/Knowledgebase/Article/View/72/24/magento-cron'>" . $this->__("Learn more") . "</a>";
            } else {
                ?>
                <table>
                <?php foreach ($crontabConfig as $crontabRow){ ?>
                    <tr>
                        <td style="padding: 0px 5px;"><?php echo $crontabRow['job_code'];?></td>
                        <td style="padding: 0px 5px;"><?php echo $crontabRow['status'];?></td>
                        <td style="padding: 0px 5px;"><?php echo $crontabRow['created_at'];?></td>
                    </tr>
                <?php }?>
                </table>
        
                <?php
                
                    
                
                
//                if (is_array($crontabConfig)){
//                    echo implode("<br/>", $crontabConfig);
//                } else {
//                    echo $crontabConfig;
//                }
            }
            ?></td>
        </tr>
    </table>
</div>