<?php $_items = $this->getItems(); ?>
<div class="page-title">
    <h1><?php echo Mage::helper('ebookdelivery')->__('My Devices') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->toHtml() ?>
<?php echo $this->getChildHtml('pager'); ?>
<?php if(count($_items)): ?>
    <table class="data-table" id="my-ebookdelivery-table">
        <col width="1" />
        <col width="1" />
        <col />
        <col width="1" />
        <col width="1" />
        <thead>
            <tr>
                <th><?php echo Mage::helper('ebookdelivery')->__('Type') ?></th>
                <th><?php echo Mage::helper('ebookdelivery')->__('Nickname') ?></th>
                <th><?php echo Mage::helper('ebookdelivery')->__('Delivery Email') ?></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <?php $_odd = ''; ?>
            <?php foreach ($_items as $_item): ?>
                <tr>
                    <td><?php echo $this->getDeviceType($_item) ?></td>
                    <td><?php echo $this->escapeHtml($_item->getDeviceNickname()) ?></td>
                    <td><?php echo $this->escapeHtml($_item->getDeviceEmail()) ?></td>
                    <td><a href="">Remove</a></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <script type="text/javascript">decorateTable('my-ebookdelivery-table')</script>
<?php else: ?>
    <p><?php echo Mage::helper('ebookdelivery')->__('You have not added any delivery devices yet.'); ?></p>
<?php endif; ?>
<?php echo $this->getChildHtml('pager'); ?>
<div class="buttons-set">
    <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
</div>