<?php $_items = $this->getItems(); ?>
<div class="page-title">
    <h1><?php echo Mage::helper('ebookdelivery')->__('Add New Device') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->toHtml() ?>
<div class="col-sm-12 col-lg-8">
    <form action="<?php echo $this->getFormActionUrl() ?>" method="post">
        <?php echo $this->getBlockHtml('formkey') ?>
        <?php echo $this->getChildHtml('devices'); ?>
    </form>
</div>
<div class="buttons-set">
    <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
</div>