<?php
class SteveB27_GoodReads_Model_Resource_Review extends Mage_Core_Model_Resource_Db_Abstract
{
	public function _construct()
    {
        $this->_init('goodreads/review','review_id');
    }

    public function deleteReviewsByProductId($productId){
        return $this;
    }

    public function save(Mage_Core_Model_Abstract $object)
    {
        return parent::save($object); // TODO: Change the autogenerated stub
    }
}