<?php
  $_helper = $this->helper('catalog/output');
  $_author = Mage::getModel('publish/author')->load($author_id);
?>
<div class="collapsible mobile-collapsible">
	<h6 class="block-title heading"><?php echo $widget_title;?></h6>
	<p>
		<a href="<?php echo $_author->getAuthorUrl() ?>" target="_self">
			<img title="<?php echo $this->stripTags($_author->getName(), null, true) ?>" alt="<?php echo $this->__('Author') . ' ' . $this->stripTags($_author->getName(), null, true) ?>" src="<?php echo Mage::helper('publish/image')->init($_author, 'image')->resize(200) ?>" />
		</a>
	</p>
	<h2 style="text-align: center;"><?php echo $this->stripTags($_author->getName(), null, true) ?></h2>
	<p>&nbsp;</p>
</div>