<?php
$_coreHelper = $this->helper('core');
$checkoutHelper = Mage::helper('onestepcheckout/checkout');
?>
<div id="header-cart">
  <div class="cart_container" style="background: url(https://stage.entangledpublishing.com.vhost.zerolag.com/skin/frontend/ultimo/bookstore/images/header-bg.png) no-repeat; background-size:cover;">
    <h2>My cart</h2>
    <div class="cart_details no_border">
      <div class="cart_lft"><span> <span class="checkout_total_item">
        <?=Mage::helper('checkout/cart')->getCart()->getItemsCount();?>
        </span> <img src="https://stage.entangledpublishing.com.vhost.zerolag.com/skin/frontend/ultimo/bookstore/images/cart-large.png"></span> </div>
      <div class="cart_rht">
        <h5>Cart Subtotal: <span> <span class="price"><?php echo $this->helper('checkout')->formatPrice(Mage::getSingleton('checkout/cart')->getQuote()->getGrandTotal()); ?> USD</span></span></h5>
        <h6>your books are available for immediate download.</h6>
      </div>
      <div class="grand_total_amount"> Order Total: <span class="price"><?php echo $this->helper('checkout')->formatPrice(Mage::getSingleton('checkout/cart')->getQuote()->getGrandTotal()); ?> USD</span> </div>
      <div class="clearfix"></div>
    </div>
  </div>
  <div class="living_holder">
    <ol id="cart-sidebar" class="mini-products-list clearer">
      <?php foreach($this->getItems() as $item): ?>
      <div class="living_container">
        <div class="living_feild">
          <li class="item"> <span class="item_img"><img src="<?=$this->helper('catalog/image')->init($item->getProduct(),'small_image')->resize(50,50);?>" width="50" height="50" alt="<?=$item->getName();?>"/></span>
            <div class="product-details">
              <p class="product-name">
                <?=$item->getName();?>
              </p>
             <?php /*?> <p>
                <?=$item->getQty();?>
                x $
                <?=$item->getPrice();?>
                USD </p><?php */?>
            </div>
            <span class="item_price">
            <?=$item->getPrice();?>
            USD</span> <span class="item_quantity">
            <table>
              <tr>
                <td class="editcart"><a href="#" class="subsqty" name="substract"></a></td>
                <td class="qty" nowrap><input type="hidden" value="<?php echo $item->getQty(); ?>" id="qty_<?php echo $item->getId(); ?>" name="cart[<?php echo $item->getId(); ?>][qty]" class="qtyinput" size="1" />
                  <?php //echo $item->getQty(); ?></td>
                <td class="editcart wider" nowrap><?php /*?><a href="#" class="addsqty" name="add">+</a><?php */?></td>
              </tr>
            </table>
            </span> </li>
          <div class="clearfix"></div>
        </div>
      </div>
      <?php endforeach; ?>
    </ol>
  </div>
</div>
<?php /*?><table class="onestepcheckout-summary">
    
    <?php foreach($this->getItems() as $item): ?>
    	
        <tr>
        <td class="name">
            <?php echo $item->getName(); ?>
            <?php if($checkoutHelper->settings['show_custom_options']): ?>
                <?php $options = $item->getProduct()->getTypeInstance(true)->getOrderOptions($item->getProduct()); ?>
                <?php if(isset($options['options']) && count($options['options']) > 0): ?>
                <ul class="onestepcheckout-custom-options">
                <?php foreach($options['options'] as $option): ?>
                    <li><b><?php echo $option['label'] . ':</b> ' . $option['value']; ?></li>
                <?php endforeach; ?>
                </ul>
                <?php endif; ?>

                <?php if($item->getProduct()->isConfigurable()): ?>

                <?php
                $configurable_options = $item->getProduct()->getTypeInstance(true)->getSelectedAttributesInfo($item->getProduct());
                ?>

                <?php if(is_array($configurable_options) && count($configurable_options) > 0): ?>
                <ul class="onestepcheckout-custom-options">
                <?php foreach($configurable_options as $option): ?>
                    <li><b><?php echo $option['label']; ?>:</b> <?php echo $option['value']; ?></li>
                <?php endforeach; ?>
                </ul>
                <?php endif; ?>

                <?php endif; ?>

            <?php endif; ?>
        </td>
        <td class="editcart">
            <a href="#" class="subsqty" name="substract">-</a>
        </td>
        <td class="qty" nowrap>
                <input type="hidden" value="<?php echo $item->getQty(); ?>" id="qty_<?php echo $item->getId(); ?>" name="cart[<?php echo $item->getId(); ?>][qty]" class="qtyinput" size="1" />
                <?php echo $item->getQty(); ?>
        </td>
        <td class="editcart wider" nowrap>
            <a href="#" class="addsqty" name="add">+</a>
        </td>
        <td class="total">
            <?php if($checkoutHelper->settings['display_tax_included']): ?>
            <?php echo $this->helper('checkout')->formatPrice($this->helper('checkout')->getSubtotalInclTax($item)); ?>
            <?php else: ?>
            <?php echo $this->helper('checkout')->formatPrice($item->getRowTotal()); ?>
            <?php endif; ?>
        </td>
    </tr>
    <?php endforeach; ?>
</table><?php */?>
<?php /*?><table class="onestepcheckout-totals">
    <?php echo $this->renderTotals(); ?>
    <?php echo $this->renderTotals('footer'); ?>
</table><?php */?>
<script type="text/javascript">
//<![CDATA[
var total = <?php echo $this->getGrandTotal();?>;
if(payment.reloadcallback){
    var url = '<?php echo $this->getUrl('onestepcheckout/ajax/paymentrefresh', array('_secure'=>true)); ?>';
    paymentrefresh(url);
    payment.countreload = 0;
    payment.reloadcallback = false;
}

$$('a.subsqty, a.addsqty, a.removeqty').each(
    function(e){
        e.observe('click', function(e){
            e.stop();
            oscUpdateCart(e.element(), '<?php echo $this->getUrl('onestepcheckout/ajax/updatecart', array('_secure'=>true)); ?>', '<?php echo $this->getUrl('onestepcheckout/ajax/set_methods_separate', array('_secure'=>true)); ?>' );
        });
    }
);
$$('input.qtyinput').each(
    function(e){
        e.observe('change', function(e){
            e.stop();

            oscUpdateCart(e.element(), '<?php echo $this->getUrl('onestepcheckout/ajax/updatecart', array('_secure'=>true)); ?>','<?php echo $this->getUrl('onestepcheckout/ajax/set_methods_separate', array('_secure'=>true)); ?>');
        });
    }
);
//]]>
</script> 
