<?php

class Entangled_Custom_Model_Rewrite_Resource_Catalog_Product_Collection extends Mage_Catalog_Model_Resource_Product_Collection {

    /**
     * Add attribute to sort order
     *
     * @param string $attribute
     * @param string $dir
     * @return Mage_Catalog_Model_Resource_Product_Collection
     */
    public function addAttributeToSort($attribute, $dir = self::SORT_ORDER_ASC)
    {
        $customAttrs = array("mobi","pdf","epub");
        if ($attribute == 'publish_author' && $this->isEnabledFlat()) {
            $authorNameAttribute = Mage::getModel('eav/config')->getAttribute('author', 'name');
            $authorNameAttributeTable = $authorNameAttribute->getBackend()->getTable();
            $authorNameAttributeId = $authorNameAttribute->getAttributeId();
            $this->getSelect()->join(array('author_varchar'=>$authorNameAttributeTable),
                                     'author_varchar.entity_id = e.publish_author AND author_varchar.attribute_id = '.$authorNameAttributeId,
                                     array('author_name'=>'author_varchar.value')
            );
            $this->getSelect()->order("author_name");
            return $this;
        }elseif(in_array($attribute,$customAttrs)){
            $this->getSelect()->order($attribute." ".$dir);
            return $this;
        }

        return parent::addAttributeToSort($attribute, $dir);
    }

    public function setOrder($attribute, $dir = 'desc')
    {
        return parent::setOrder($attribute, $dir); // TODO: Change the autogenerated stub
    }

}